default: &default
  adapter: postgresql
  timeout: 50000
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: min-skill_development
  username: devuser

test:
  <<: *default
  database: min-skill_test
  username: devuser

production:
  <<: *default
  database: min-skill_production
